[package]
name = "wasp"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
wasp-core = { path = "../wasp-core" }
wasp-http = { path = "../wasp-http" }
