[package]
name = "wasp-core"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
edition = "2018"

[dependencies]
wasp-abi = { path = "../wasp-abi" }
wasp-status-code = { path = "../wasp-status-code", default-features = false }
