[package]
name = "wasp-status-code"
version = "0.1.0"
authors = ["Cameron Bytheway <bytheway.cameron@gmail.com>"]
edition = "2018"

[features]
default = ["std"]
std = []

[dependencies]
num-traits = "0.2"
num-derive = "0.2"
